"""Migración inicial definitiva

Revision ID: 762ba7a7cd49
Revises: f3f5f94e3fc7
Create Date: 2025-06-09 10:09:24.711031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762ba7a7cd49'
down_revision = 'f3f5f94e3fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('turno_odontologo_id_fkey'), type_='foreignkey')
        batch_op.drop_column('odontologo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odontologo_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('turno_odontologo_id_fkey'), 'odontologo', ['odontologo_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
