"""Descripción del cambio

Revision ID: 7ada1b0709ca
Revises: f08383c7009a
Create Date: 2025-06-09 10:25:35.706398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ada1b0709ca'
down_revision = 'f08383c7009a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odontologo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'odontologo', ['odontologo_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('odontologo_id')

    # ### end Alembic commands ###
