"""Migración inicial definitiva

Revision ID: f3f5f94e3fc7
Revises: 270cf85835c8
Create Date: 2025-06-09 09:13:17.009361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f5f94e3fc7'
down_revision = '270cf85835c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tratamiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))

    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odontologo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'odontologo', ['odontologo_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('odontologo_id')

    with op.batch_alter_table('tratamiento', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
